export const GET_DATA= "GET_DATA";
export const REQ_DATA= "REQ_DATA,"
export const ERR_DATA= "ERR_DATA"
export const SORT_DATA= "SORT_DATA"

export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'
export const GET_PRODUCT_DETAILS_RESET = 'GET_PRODUCT_DETAILS_RESET'

// export const GET_PRODUCT_DETAILS_RESET = 'getProductDetailReset'