export const GET_PRODUCT_DETAILS_RESET= "GET_PRODUCT_DETAILS_RESET"
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TOCART_ERROR = "ADD_TOCART_ERROR" 
export const REMOVE_CART = "REMOVE_CART";
export const CART_RESET = "CART_RESET";



// export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
// export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
// export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'